### ISSUE TITLE
Reorder regex patterns so they all have a chance of returning a match?

### ISSUE THREAD

**Issue by JayBizzle** [JayBizzle/Crawler-Detect#10]
Some regex patterns will never match.

For example...
```
'Googlebot',
'Googlebot-Image',
'Googlebot-Mobile',
```

A user-agent that contains `Googlebot-Image` will never match that specific regex, because the more generic `Googlebot` regex matches first.

In this instance, should we remove `Googlebot-Image` and `Googlebot-Mobile` or keep them in for verbosity and reorder them?

**Comment by Kryptonit3** [comment]
yes, they are pointless.
