### ISSUE TITLE
FEVER user agent

### ISSUE THREAD

**Issue by alberto-bottarini** [JayBizzle/Crawler-Detect#106]
Hi,
i found an issue about this UA:

`Mozilla/5.0 (Linux; Android 5.1; FEVER Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.105 Mobile Safari/537.36`

I'm not sure this is a crawler. I think this is a valida UA provided by this company: wikomobile.com.
You can read something here: http://www.tera-wurfl.com/explore/?action=wurfl_id&id=wiko_fever_ver1

What do you think?

**Comment by JayBizzle** [comment]
Good catch, it is indeed a false positive.

I shall fix later this evening...

**Comment by JayBizzle** [comment]
Fixed. Thanks for reporting!
