### ISSUE TITLE
Updated & Sorted List

### ISSUE THREAD

**Issue by ebbmo** [JayBizzle/Crawler-Detect#112]
Hi guys,

Awesome list - really appreciate it!
I have analyzed our dataset of incoming calls and merged some bots, that were not in your list.
In addition I have sorted the list, since I am doing a binary search through it, but the list is currently not 'sorted' according to ASCII standards.

Sorry for not pointing out which entries I have added :( but I was tunnel-visioning and forgot to save them...

Hope it still helps and that you can use these / update your list.

Cheers,
ebbmo
[botlist.txt](https://github.com/JayBizzle/Crawler-Detect/files/374100/botlist.txt)

**Comment by JayBizzle** [comment]
Thanks for this.

There was one new bot in the list you provided. The rest were new user agents we can test existing bot regexes against.
