### ISSUE TITLE
Detect SogouMobileBrowser 

### ISSUE THREAD

**Issue by sjay23** [JayBizzle/Crawler-Detect#117]
Good day! I use your script, very good work! But faced with such a problem. Home comes a lot of users with a browser SogooMobileBrovser and it is certainly not bots. How to make an exception for them, what would use the current versions of your repository?

Example:
`Mozilla/5.0 (Linux; U; Android 5.1; zh-cn; 1501_M02 Build/LMY47D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 SogouMSE,SogouMobileBrowser/4.1.0`

**Comment by JayBizzle** [comment]
Hi,

Thanks for reporting this. We can confirm this is indeed a false positive.

We have a fix ready that will be released later today.

👍

**Comment by sjay23** [comment]
Thank you! I will wait!  :+1:

**Comment by MaxGiting** [comment]
I have released a new version that fixes this false positive. Thanks for reporting it! 👍
