### ISSUE TITLE
Why Slurp and not Yahoo! Slurp

### ISSUE THREAD

**Issue by tangar76** [JayBizzle/Crawler-Detect#121]
Crawler-Detect started detect `Slurp` crawler instead of `Yahoo! Slurp`.
User agent: Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)

Can you, please, make this lib detect such user agents as `Yahoo! Slurp` crawler.

PS: http://www.useragentstring.com/ knows `Yahoo! Slurp` and does not know `Slurp`.

**Comment by JayBizzle** [comment]
Surely `slurp` matches `Yahoo! Slurp`?

This library is not for telling which bot visited, just whether the client is a bot...or not
