### ISSUE TITLE
monperrus/crawler-user-agents repository

### ISSUE THREAD

**Issue by AgelxNash** [JayBizzle/Crawler-Detect#122]
Look at https://github.com/monperrus/crawler-user-agents

**Comment by JayBizzle** [comment]
Hi @AgelxNash 

Thanks for the suggestion.

However, if you investigate that repo further, you will see I have been a contributor over there in the past, and in fact, if you look at the orignal source of that list which can be [found here](http://www.monperrus.net/martin/list+of+robot+user+agents) and look in the comments (at the bottom of the page), you will see it was me that originally suggested that the list should be made into a GitHub repo 👍
