### ISSUE TITLE
2ip.ru signature 

### ISSUE THREAD

**Issue by AgelxNash** [JayBizzle/Crawler-Detect#126]
> 2ip.ru CMS Detector (http://2ip.ru/cms/)
![Alt text](https://monosnap.com/file/Dqzefuf1DpBWMEHtGTMPP8UX1uzUNE.png)

**Comment by MaxGiting** [comment]
Thanks for reporting this. I will add this in the next release later today.

**Comment by MaxGiting** [comment]
I've released a new version with your find. Thanks
