### ISSUE TITLE
Branch.io Crawler is not in the list

### ISSUE THREAD

**Issue by costasapostolopoulos** [JayBizzle/Crawler-Detect#127]
Branch.io has a crawler that scrapes metadata and has a `Branch-Passthrough` user agent.

**Comment by costasapostolopoulos** [comment]
seems like there are two user-agents: `Branch-Passthrough`

**Comment by MaxGiting** [comment]
Thanks for reporting these. I will add them in the next release later today.

**Comment by MaxGiting** [comment]
I've released a new version with your find. Thanks
