### ISSUE TITLE
New bots

### ISSUE THREAD

**Issue by NetruN** [JayBizzle/Crawler-Detect#137]
Could you please add "OnPageBot" and "Uptrends"? Thanks.

**Comment by JayBizzle** [comment]
Sure! OnPageBot is already detected but we can definitely add Uptrend. Do you have a full user agent for it?

**Comment by JayBizzle** [comment]
@NetruN Any chance of a full use agent for Uptrend that we can use to test. Have done a quick Google search for it, but couldn't find anything.

Thanks

**Comment by Spywer** [comment]
Please add

**Comment by JayBizzle** [comment]
@Spywer that is already detected. (Nearly) every user agent with the string `bot` in it is generically detected

**Comment by effeks** [comment]
Hi, please add "iplabel", which looks to be some kind of application monitor system:
`Mozilla/5.0 (iplabel; Windows NT 6.3; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0`

**Comment by JayBizzle** [comment]
@effeks Thanks for reporting, I have added this in #163

**Comment by kratkyzobak** [comment]
Hi, I'm sending some user agents from our logs, which seems to be bots, but library did not match them.

Some of them are library names (such as PHP or WinHTTP), which are in most cases used for robot like access. But I don't know politics of this lib (if most cases is god enough).

```
WinHTTP
WebClient/1.0 
Test Certificate Info 
RSSOwl/2.2.1.201312301314 (Windows; U; en) 
PHP 
CATExplorador/1.0beta (sistemes at domini dot cat; http://domini.cat/catexplorador.html) 
Microsoft Data Access Internet Publishing Provider Protocol Discovery 
Microsoft-WebDAV-MiniRedir/10.0.10586 
Microsoft-WebDAV-MiniRedir/10.0.14393 
Microsoft-WebDAV-MiniRedir/5.1.2600 
Microsoft-WebDAV-MiniRedir/6.0.6001 
Microsoft-WebDAV-MiniRedir/6.1.7601 
Microsoft-WebDAV-MiniRedir/6.3.9600 
Mozilla/4.0 (compatible;)
Mozilla/4.0 (compatible; Synapse) 
Mozilla/5.0 (compatible)
```

**Comment by JayBizzle** [comment]
Thanks @kratkyzobak, we will look at adding those over the next few days!

**Comment by MaxGiting** [comment]
@kratkyzobak I have added most of these to the latest release. Below I've marked which have been added. Some I felt were too generic like Mozilla/5.0 (compatible). I want to take a further look into the PHP and WinHTTP ones though. 

WinHTTP
~~WebClient/1.0~~
~~Test Certificate Info~~ 
~~RSSOwl/2.2.1.201312301314 (Windows; U; en)~~
PHP 
~~CATExplorador/1.0beta (sistemes at domini dot cat; http://domini.cat/catexplorador.html)~~ 
~~Microsoft Data Access Internet Publishing Provider Protocol Discovery~~ 
~~Microsoft-WebDAV-MiniRedir/10.0.10586~~ 
~~Microsoft-WebDAV-MiniRedir/10.0.14393~~ 
~~Microsoft-WebDAV-MiniRedir/5.1.2600~~ 
~~Microsoft-WebDAV-MiniRedir/6.0.6001~~ 
~~Microsoft-WebDAV-MiniRedir/6.1.7601~~ 
~~Microsoft-WebDAV-MiniRedir/6.3.9600~~ 
Mozilla/4.0 (compatible;)
Mozilla/4.0 (compatible; Synapse) 
Mozilla/5.0 (compatible)
