### ISSUE TITLE
Google Docs Crawler

### ISSUE THREAD

**Issue by JanKrohn-Khalibre** [JayBizzle/Crawler-Detect#138]
I found a new crawler in my server logs:

Mozilla/5.0 (compatible; GoogleDocs; apps-spreadsheets; +http://docs.google.com)

**Comment by JayBizzle** [comment]
Thanks for reporting, I have added this and it will be available in the next release!

❤️

**Comment by JanKrohn-Khalibre** [comment]
That was really fast. Awesome! Thank you!
