### ISSUE TITLE
acapbot

### ISSUE THREAD

**Issue by JanKrohn-Khalibre** [JayBizzle/Crawler-Detect#139]
Hi! I just detected another bot in my server logs:

Mozilla/5.0 (compatible;acapbot/0.1)

**Comment by JanKrohn-Khalibre** [comment]
Here's one more:
Mozilla/5.0 (compatible; proximic; +http://www.proximic.com/info/spider.php)

**Comment by JayBizzle** [comment]
Thanks.

Both those are already detected by the generic regex (anything with the string bot/spider/crawler etc)

I have add the user agents to the test though, so thanks for that.

👍

**Comment by JanKrohn-Khalibre** [comment]
They work fine indeed. Thanks for verifying. They merely tried to crawl a page that a real user visited at the same time, so I mistakenly concluded that the crawlers triggered some unwanted action. 😳
