### ISSUE TITLE
Create extension please for YII2

### ISSUE THREAD

**Issue by semiromid** [JayBizzle/Crawler-Detect#152]
Create extension please for YII2

**Comment by nicolasmure** [comment]
Ouch, this is kind of rude.

Even if the library is not wrapped for YII2, you can still use it in a standalone way : https://github.com/JayBizzle/Crawler-Detect#installation

**Comment by semiromid** [comment]
Yes, i know. Thank You.

**Comment by JayBizzle** [comment]
https://github.com/AlikDex/yii2-crawler-detect
