### ISSUE TITLE
Why need -  // Pass a user agent as a string ?

### ISSUE THREAD

**Issue by semiromid** [JayBizzle/Crawler-Detect#153]
Why need -  // Pass a user agent as a string ?

it detect all useragent?
`$CrawlerDetect->isCrawler()`

AND

it not detect all useragent?
`$CrawlerDetect->isCrawler('Mozilla/5.0 (compatible; Sosospider/2.0; +http://help.soso.com/webspider.htm)')`

```
// Check the user agent of the current 'visitor'
if($CrawlerDetect->isCrawler()) {
    // true if crawler user agent detected
}

// Pass a user agent as a string
if($CrawlerDetect->isCrawler('Mozilla/5.0 (compatible; Sosospider/2.0; +http://help.soso.com/webspider.htm)')) {
    // true if crawler user agent detected
}
```

**Comment by nicolasmure** [comment]
When the `isCrawler` function is called without parameters, the lib is checking against the UA (User-Agent) of the current request.

You can pass a UA as parameter to check if this UA belongs to a crawler or to a web browser. For instance, you log all the accesses to your site and you want to know the human / bot access ratio so you can use the logged UA here.

**Comment by JayBizzle** [comment]
Thanks @nicolasmure

**Comment by semiromid** [comment]
Ok. Thank You.
