### ISSUE TITLE
How can I get bot information?

### ISSUE THREAD

**Issue by infete1001** [JayBizzle/Crawler-Detect#156]
Hi

I am interested in knowing which bot came to my website and when did it come and and how many times in a day?

Can you add these methods?

TIA

**Comment by alister** [comment]
That's what access logs are for.

**Comment by infete1001** [comment]
@alister where these access logs go?

**Comment by JayBizzle** [comment]
The main purpose of Crawler-Detect is to return `true` or `false` if the user agent is a known bot or not.

Any logging you require will need to be built manually
