### ISSUE TITLE
detect new crawler

### ISSUE THREAD

**Issue by majidramzi** [JayBizzle/Crawler-Detect#178]
I think I found a new crawler.
information of this crawler is : `AppManager RPT-HTTPClient/0.3-3E`
is that true?

**Comment by JayBizzle** [comment]
Yes, looks good. Thanks

Do you want to create a Pull Request?

**Comment by majidramzi** [comment]
Thanks.

Yep 👍 To Pull Request, should I clone repository and make a new branch?

**Comment by JayBizzle** [comment]
Fork this repo.

Clone your fork.

Make your changes on your fork.

Then make a Pull Request.

👍
