### ISSUE TITLE
New crawler

### ISSUE THREAD

**Issue by pothead32uk** [JayBizzle/Crawler-Detect#183]
Hi
This crawler visited my site today:

Virusdie crawler/3.0

Hope you can include it.

Thanks.

**Comment by JayBizzle** [comment]
As you can see, this crawler is already being detected...

http://crawlerdetect.io/?q=Virusdie%20crawler/3.0

...and we already have it in out test suite [here](https://github.com/JayBizzle/Crawler-Detect/blob/master/tests/crawlers.txt#L1128)

Thanks for taking the time to report it though.

Was there a reason you thought it wasn't being detected?

**Comment by pothead32uk** [comment]
Yeah

I looked through your big list [https://github.com/JayBizzle/Crawler-Detect/blob/master/tests/crawlers.txt], and only 2.1 was included.
