### ISSUE TITLE
Incorrect agent result - its a slack preview bot

### ISSUE THREAD

**Issue by saurabh-diffion** [JayBizzle/Crawler-Detect#202]
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Slack/1.2.6 Chrome/45.0.2454.85 AtomShell/0.34.3 Safari/537.36 Slack_SSB/1.2.6

**Comment by JayBizzle** [comment]
Awesome, thanks! ❤️ 

Sorted in #203 👍
