### ISSUE TITLE
Incorrect agent result

### ISSUE THREAD

**Issue by camera-man** [JayBizzle/Crawler-Detect#204]
null or an empty string are 2 user agent cases for bad bots. Nice to handle them too

**Comment by JayBizzle** [comment]
Thanks for taking the time to report this.

I'm not entirely sure that assuming `null` and empty string are bots is a good idea. I agree in most cases they will probably be bots, but i think a lot of guess work is happening here. We only want to detect bots that specifically say they are a bot.

Thanks
