### ISSUE TITLE
Incorrect agent result

### ISSUE THREAD

**Issue by gDemous** [JayBizzle/Crawler-Detect#207]
Mozilla/5.0 (Linux; Android 6.0.1; LG-K100 Build/MXB48T; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/50.0.2661.86 Mobile Safari/537.36 YandexSearch/5.75

**Comment by JayBizzle** [comment]
Are you sure, we seem to be correctly detecting this as a bot

https://crawlerdetect.io/?q=Mozilla/5.0%20(Linux;%20Android%206.0.1;%20LG-K100%20Build/MXB48T;%20wv)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Version/4.0%20Chrome/50.0.2661.86%20Mobile%20Safari/537.36%20YandexSearch/5.75

**Comment by gDemous** [comment]
Yes, this is the CPC click from mobile app Yandex Search. Bots from yandex are (which I know):
YandexBot
YandexImages
YandexMobileBot
YandexMetrika
YandexImageResizer
YandexPagechecker
YandexCatalog
YandexBlogs
YandexVideo
YandexMedia
YandexAccessibilityBot
YandexVideoParser
YandexFavicons
YandexDirect (not sure about this, but there is an referrer to http://yandex.com/bots)
Yandex (Old one. Last appears in analytics is about year ago)

**Comment by JayBizzle** [comment]
Ah, so you are saying that `YandexSearch/5.75` in not a bot?

**Comment by gDemous** [comment]
Yes :)

**Comment by JayBizzle** [comment]
Okay, thanks, we will look into it 👍

**Comment by gDemous** [comment]
Thanks
