### ISSUE TITLE
Incorrect user agent result: HubPages

### ISSUE THREAD

**Issue by kamdhenu** [JayBizzle/Crawler-Detect#212]
User Agent: `HubPages V0.2.2 (http://hubpages.com/help/crawlingpolicy)`
Result: `HubPages V0.2.2 (http://hubpages.com/help/crawlingpolicy`

I would also like to point out parsing error in User Agents like `WordPress/4.8; http://xyz.com` or `redback/v0-570-g26f8c96`, it always includes the trailing slash in the result, e.g. WordPress/ or Redback/

May be cleaning out the result with below code will help:
`trim(preg_replace('/[^A-Za-z0-9\-\_\.]/', ' ', $result))`

**Comment by JayBizzle** [comment]
Would you like to submit a PR with the proposed changes?

Thanks

**Comment by kamdhenu** [comment]
Sorry but I'm still a novice PHP developer and yet to learn how to work with Git :-(

But, what I'm proposing here is changing the method `getMatches();` inside "Jaybizzle\CrawlerDetect\CrawlerDetect" as below:

`public function getMatches()
    {
        return isset($this->matches[0]) ? trim(preg_replace('/[^A-Za-z0-9\-\_\.]/', ' ', $this->matches[0])) : null;
    }`

It will filter out any unwanted special characters and white spaces. I'm not sure, if any detected bot does really requires special characters, except a - (minus sign) and _ (underscore) .

**Comment by JayBizzle** [comment]
Sorry for the delayed response.

I see where you are coming from, but the `getMatches()` method is not really used to return the exact bot that was detected, but more to return the exact portion of the user agent that caused the true response.

It would be nice to by able to have magic methods, such as `isHubPages()` but this would require us keeping a more complex database of bots and the beauty of this library is it's simplicity.

Always open to PRs though.

Thanks
