### ISSUE TITLE
May you port this to use with tuckey urlrewrite or atleast Java

### ISSUE THREAD

**Issue by Sumit-Chakole** [JayBizzle/Crawler-Detect#216]
The tool that I am looking for and necessary code I have written is mentioned in this stackoverflow [question](https://stackoverflow.com/q/45059783/2074378)

Tuckey Url Rewrite is java (tomcat) port of famous apache lib mod_rewrite, it could be found [here](https://github.com/paultuckey/urlrewritefilter).

**Comment by MaxGiting** [comment]
Sorry we are not planning on porting this library ourselves into other languages. There is an open PR relating to ports to C and GO https://github.com/JayBizzle/Crawler-Detect/pull/62 but no Java implementations that I know of for now.
