### ISSUE TITLE
Missing "Google favicon" detection ?

### ISSUE THREAD

**Issue by castevinz** [JayBizzle/Crawler-Detect#22]
I see this in my SERVER (PHP) variable, with no detection : 
"[HTTP_USER_AGENT] => Google favicon"

Could you manage its detection on a future tag ?
Thx

**Comment by JayBizzle** [comment]
Yeah, no problem. I'll look into it an get something released in the next few days.

Pull requests welcome :wink:

**Comment by castevinz** [comment]
https://github.com/JayBizzle/Crawler-Detect/pull/23

**Comment by JayBizzle** [comment]
Note to self: add this to UA tests

`Mozilla/5.0 (Windows NT 6.1; rv:6.0) Gecko/20110814 Firefox/6.0 Google favicon`

**Comment by castevinz** [comment]
Done ;-)

**Comment by JayBizzle** [comment]
:heart:
