### ISSUE TITLE
Possible Crawler: wpif

### ISSUE THREAD

**Issue by jeisinge** [JayBizzle/Crawler-Detect#222]
We have seen a user agent of `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.21 (KHTML, like Gecko) wpif Safari/537.21` that appears to be non-human.  In particular, https://www.webmasterworld.com/search_engine_spiders/4785385.htm appears to agree.  [Browscap](http://browscap.org/ua-lookup) does not.  Thoughts?

**Comment by JayBizzle** [comment]
It certain smells of robot, and given the info in the linked thread, I'd go with bot. Also from that thready, it may be worth adding `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.21 (KHTML, like Gecko) imgsizer Safari/537.21`

You fancy doing another PR?

Thanks

**Comment by jeisinge** [comment]
Sure.  I'll review our logs some more around `imgsizer` and `wpif` and get a PR to you today or Monday!

**Comment by JayBizzle** [comment]
Fixed in #223

**Comment by jeisinge** [comment]
It has been created as https://github.com/JayBizzle/Crawler-Detect/pull/223 .  This also required removing a `wpif` entry from devices.

I can't speak for others, but this user agent is definitely showing nonhuman-like patterns on our site.

**Comment by JayBizzle** [comment]
Good work, thanks
