### ISSUE TITLE
Class 'Jaybizzle\CrawlerDetect\CrawlerDetect' not found

### ISSUE THREAD

**Issue by HerrimanCoder** [JayBizzle/Crawler-Detect#224]
I have created a CrawlerDetect folder in my php app folder and I extracted the github zip in there like so:

- raw
- src
- composer.json
- export.php
- LICENSE
- README.md

I have this at the top of my php script file:

```
include_once("CrawlerDetect/export.php");
use Jaybizzle\CrawlerDetect\CrawlerDetect;
$CrawlerDetect = new CrawlerDetect;

if($CrawlerDetect->isCrawler()) {
	writeme("we got a crawler!");
}else{
	writeme("we got a human!");
}
```

When I run my php script in a browser, I get Class 'Jaybizzle\CrawlerDetect\CrawlerDetect' not found. On github for this library it mentions running cmd-line stuff, etc. Can I not just dump the files in my directory and reference it at the top of my script? What am I doing wrong?

**Comment by JayBizzle** [comment]
You can use it like this, but you really should be using `composer` to be dealing with the autloading

```php
require 'src/CrawlerDetect.php';
require 'src/Fixtures/AbstractProvider.php';
require 'src/Fixtures/Crawlers.php';
require 'src/Fixtures/Exclusions.php';
require 'src/Fixtures/Headers.php';

$CrawlerDetect = new Jaybizzle\CrawlerDetect\CrawlerDetect;

if ($CrawlerDetect->isCrawler()) {
	echo 'we got a crawler!';
} else {
	echo 'we got a human';
}
```
