### ISSUE TITLE
Missing LinkedIn user agent

### ISSUE THREAD

**Issue by viktorivanov** [JayBizzle/Crawler-Detect#228]
Hi,
as I am aware LinkedIn's bot uses `LinkedInBot/1.0` as its user agent, but It seems to be missing in `Crawlers.php`

I could make a PR.

Thank you,
Viktor

**Comment by JayBizzle** [comment]
It is already detected as a bot because it has the string `bot` in the user agent.

https://crawlerdetect.io/?q=LinkedInBot/1.0

**Comment by viktorivanov** [comment]
Ok, sorry to bother.

**Comment by JayBizzle** [comment]
no worries 👍
