### ISSUE TITLE
Incorrect agent result

### ISSUE THREAD

**Issue by everfluxx** [JayBizzle/Crawler-Detect#230]
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.21 (KHTML, like Gecko) wpif Safari/537.21

This **is** a bot U-A.

**Comment by JayBizzle** [comment]
I presume the `wpif` string is the identifier here?

**Comment by everfluxx** [comment]
Yep.

**Comment by JayBizzle** [comment]
It looks like i hadn't update crawlerdetect.io with the latest depencies becuase `wpif` was added a couple of months ago in PR #223

Website now update and reports this user agent correctly as a bot 👍 

https://crawlerdetect.io/?q=Mozilla/5.0%20(X11;%20Linux%20x86_64)%20AppleWebKit/537.21%20(KHTML,%20like%20Gecko)%20wpif%20Safari/537.21
