### ISSUE TITLE
Incorrect agent result: PRTG network monitor

### ISSUE THREAD

**Issue by alphestdev** [JayBizzle/Crawler-Detect#231]
I don't know if you consider (or should consider) server monitoring tools bots or not, but just in case, this one passes your check as not a bot:
`Mozilla/5.0 (compatible; PRTG Network Monitor (www.paessler.com); Windows)`

**Comment by JayBizzle** [comment]
Looks good, I'll try and get that added this week unless you fancy doing a pull request in the meantime.

Thanks
