### ISSUE TITLE
Google HTTP java client

### ISSUE THREAD

**Issue by romaricdrigon** [JayBizzle/Crawler-Detect#24]
Hi,

I got several hits from `Google-HTTP-Java-Client\/1.17.0-rc (gzip)` User-Agent. That one is not considered a bot. Stricto sensu, it is not since it's only the medium, but it denotes a programmatic connection and then eventually a crawler.
What about adding this one?

**Comment by romaricdrigon** [comment]
I guess that one could be added since we already have `phpcrawler` and so on in regexes ; though I'm waiting on my other PR not to have a conflict.

**Comment by JayBizzle** [comment]
Yes, I think it is definitely worth adding :+1:

**Comment by romaricdrigon** [comment]
Good, then I'm adding it to my current PR.
