### ISSUE TITLE
Spoofing the user agent

### ISSUE THREAD

**Issue by cr101** [JayBizzle/Crawler-Detect#258]
First of all, thank you for your software.

A lot of bots tend to spoof user agents and some do it for legitimate reasons (i.e. they only want to crawl mobile content), while others simply don't want to be identified as bots. Even worse, some bots spoof legitimate/polite bot agents, such as the user agents of google, microsoft and other crawlers which are generally considered polite.

How reliable is detecting bots/crawlers/spiders via the user agent?

**Comment by JayBizzle** [comment]
As you have correctly pointed out, the user agent can be easily spoofed. Nothing we can do about that.

We do checked a few other header other than the user agent though to detect some bots i.e. GoogleBot sometimes spoofs the user agent but identifies itself in the for of the FROM header. 

IP address checking would be the next step. We have explored the idea, but decided it would be too hard to maintain.
