### ISSUE TITLE
Question about a Regex

### ISSUE THREAD

**Issue by dliebner** [JayBizzle/Crawler-Detect#266]
What's the point of the `[a-z0-9\-_]*` component of the `[a-z0-9\-_]*(bot|crawler|archiver|transcoder|spider|uptime|validator|fetcher)` pattern? It's a `*` pattern, so since it's entirely optional, shouldn't it just be excluded?

**Comment by gplumb** [comment]
* is not a wildcard in regex. It means "some or none" of the characters between the brackets. HTH!

**Comment by gplumb** [comment]
(Meaning that other characters may appear begore the word bot or crawler, etc...)

**Comment by dliebner** [comment]
Yes, I understand. My point is that since it's some or none, it's optional, so `5bot` and `bot` would match all the same even if the pattern was simply `(bot|crawler|archiver|transcoder|spider|uptime|validator|fetcher)`.

**Comment by JayBizzle** [comment]
@dliebner You got it. Its so we can return the whole bot name

These show the differences...
https://regex101.com/r/uJab18/1
https://regex101.com/r/uJab18/2
