### ISSUE TITLE
Add JuziBrowser

### ISSUE THREAD

**Issue by pcmanprogrammeur** [JayBizzle/Crawler-Detect#269]
Hi,
Here is a new spider JuziBrowser :
```
Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; JuziBrowser)
```
Can you add this one please ?

**Comment by JayBizzle** [comment]
Thanks!

Would you like to try and create a PR to add this yourself?

**Comment by pcmanprogrammeur** [comment]
No problem ! :+1:

**Comment by JayBizzle** [comment]
#270

**Comment by jaydiablo** [comment]
JuziBrowser isn't a crawler, that UA is from the browser itself: https://github.com/browscap/browscap/issues/1505

**Comment by JayBizzle** [comment]
@jaydiablo thanks for the info, much appreciated. Will revert this 👍
