### ISSUE TITLE
Incorrect agent result

### ISSUE THREAD

**Issue by zkulbeda** [JayBizzle/Crawler-Detect#280]
Unshorten.It! /1.0 (https://unshorten.it/)

**Comment by MaxGiting** [comment]
Would you like to create a PR to fix this?

**Comment by JayBizzle** [comment]
Should have been detected here...

https://github.com/JayBizzle/Crawler-Detect/blob/55ad4b140d821c19dbaf1a6ea9d9e5ca6444ecc1/src/Fixtures/Crawlers.php#L1014

...but the regex didn't work.

Have tweaked it in 7ef42a99170efb806641189e94cc38311f7277d8
