### ISSUE TITLE
Verifying bots?

### ISSUE THREAD

**Issue by kiler129** [JayBizzle/Crawler-Detect#281]
I was wondering if the library has any way or plans to incorporate functionality of validating bots? Some of the bots (e.g. [Google Bot](https://support.google.com/webmasters/answer/80553?hl=en) and [Bing Bot](https://www.bing.com/webmaster/help/how-to-verify-bingbot-3905dc26)) offer a way to ensure that client is really the bot itself and not someone changing their UA.

This functionality will be very useful when doing some SEO optimizations (e.g. disabling dynamic pagination for bots or allowing them to see more results at once).

**Comment by gplumb** [comment]
One way to achieve this would be to perform a reverse DNS lookup of the client's IP address and see if the result is a known domain for the given bot user agent.  This could be slow (although you could of course cache the results), and still doesn't 100% guarantee that an IP address hasn't been tampered with (although the overall 'bot confidence' would be a lot higher).

Practically speaking (using your example above), is it the end of the world if a UA has been manipulated?

**Comment by kiler129** [comment]
I would see that as an option, like "strict verify", not as a default. Caching results should be a requirement I think, since when you have IP it shouldn't change. This will eliminate problem with missconfigured resolver in host OS.
Speaking about tampering with IP it's as trusted as DNS is. If you cannot trust DNS on your server you have a bigger issue I think :)

It's not end of the world, however it poses more business risk. For trusted bots we can whitelist some restrictions which are put in place to prevent abuse (e.g. captcha for extensive page visits which looks automated).

**Comment by gplumb** [comment]
The strict mode makes sense - I also take your point on the DNS server ;-)

If the lookup functionality is hidden behind an interface, then adding specific DNS servers, caching or even an in-memory dictionary (for testing) would be quite trivial. I maintain the C# port of this library, so I'll see if I can find time to add it there in the next few days and back-port it here - unless you have some php ready to roll :-)

**Comment by gplumb** [comment]
I cobbled something together, but I'm not sure how useful it's going to be.  For the larger bots like googlebot and bingbot, the lookup approach will work well, but for some of the lesser known ones (like Zauba, which runs on AWS), the reverse lookup is going to be misleading.

This may be ok for a strict mode (since it's. well. strict!) - but if the use case is for preventing abuse, then throttling may be a better solution...

**Comment by JayBizzle** [comment]
We've discussed IP checking in the past but came to the conclusion this is not something we would like to maintain in this repository. Although, a good implementation of verifying the larger bots like you mention in the first post would be worth a look at. Am open to PRs on that.

Wouldn't mind seeing your cobbled together code @gplumb perhaps you could stick it on a PR as a starting point to discuss this further 👍
