### ISSUE TITLE
Use hidden URL to determine if a connection is a bot

### ISSUE THREAD

**Issue by InquisitiveDevelopment** [JayBizzle/Crawler-Detect#285]
I was talking to an engineer at a local company some time back and he had mentioned that there were hidden products mixed in with all of the real ones that a user would never see, but a bot would crawl.

What would the possibility of adding some functionality to allow the library to be passed an IP if an IP is passed to it then requests from that IP would then have `isCrawler` return true for some set amount of time? Would some implementation of this be a sensible addition to the library?

**Comment by JayBizzle** [comment]
I think that would be out of the scope of Crawler Detect. You'd be better writing your own logic to handle this, or extending this Crawler Detect to add the added functionality. 

Thanks :+1:
