### ISSUE TITLE
Criteo (remarketing agency) bot

### ISSUE THREAD

**Issue by kratkyzobak** [JayBizzle/Crawler-Detect#289]
User agent by https://www.criteo.com/ - probably some screenshot taker.

`Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36 Pix/1.0 (Criteo; x64-criteo)`

**Comment by JayBizzle** [comment]
Nice work.

Would you like to create a PR to add this?

Thanks 👍
