### ISSUE TITLE
Detected as Trojan:Script/Cloxer.A!cl

### ISSUE THREAD

**Issue by alexhampu** [JayBizzle/Crawler-Detect#291]
For some reason Windows Defender marks one file as a trojan.

![image](https://user-images.githubusercontent.com/21214654/45584342-8a736600-b8da-11e8-803c-ed42621d3803.png)

file: **vendor\jaybizzle\crawler-detect\src\Fixtures\Crawlers.php**

**Comment by JayBizzle** [comment]
Weird. Do you have any theories as to why this may be happening?

**Comment by alexhampu** [comment]
I have no idea, this package is a dependency in the new Laravel 5.7 version, and when doing composer install, it just pops up. This is really weird as the file only contains an array of strings, nothing special, but because of that I cannot install it without marking the directory in the exception list.

**Comment by JayBizzle** [comment]
Ummmm....perhaps is it one of the strings in that array flagging it?

I don't have a Windows machine to test.  If you had the time, you could try removing some of the regexes and keep going until it is no longer flagged to find the culprit. Then we could come up with a solution 👍

**Comment by alexhampu** [comment]
> 
> 
> Ummmm....perhaps is it one of the strings in that array flagging it?
> 
> I don't have a Windows machine to test. If you had the time, you could try removing some of the regexes and keep going until it is no longer flagged to find the culprit. Then we could come up with a solution 👍

Yeah, sure. I will try to do this today and if I find it, I will make a PR.

**Comment by alexhampu** [comment]
The issue is caused by the first string: **.*Java.*outbrain**, once removed, it's not flagged anymore.

**Comment by JayBizzle** [comment]
Good work. I wonder if there is anything in particular within that string is the issue? What happens if you just remove `outbrain`?

**Comment by alexhampu** [comment]
I was playing this it now, after changing the name of the file, it started to detect it again, so there is still something affecting it.

**Comment by JanKrohn-Khalibre** [comment]
I had this issue with my own application.
The developer needs to submit it to Microsoft as a false positive. It takes about a day or so to get removed.
https://www.microsoft.com/en-us/wdsi/filesubmission?persona=SoftwareDeveloper

**Comment by alexhampu** [comment]
@JanKrohn-Khalibre I think that's the best solution, otherwise other issues may be found in the file.

**Comment by JayBizzle** [comment]
Response already...

> Thank you for your inquiry.
> 
> We have reviewed the file and we have removed the detection. 
> 
> Please try the following steps to clear cached detections and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 
> The latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
> 
> Best regards,
> Windows Defender Response

**Comment by alexhampu** [comment]
For the moment it's not picking the update, but I think this take a little time.

```
.\MpCmdRun.exe -SignatureUpdate
Signature update started . . .
Signature update finished. No updates needed
```

I think this issue can be closed now. Thank you for your time!

**Comment by JayBizzle** [comment]
Okay, if you can check in a day or 2 and report back, that would be great, thanks!

**Comment by alexhampu** [comment]
> 
> 
> Okay, if you can check in a day or 2 and report back, that would be great, thanks!

Sure, I will keep an eye on it.

**Comment by alexhampu** [comment]
A few updates have been released, one of them fixed it. Thank you for your time.

Best regards,
Alex.
