### ISSUE TITLE
tracemyfile 

### ISSUE THREAD

**Issue by alberto-bottarini** [JayBizzle/Crawler-Detect#296]
https://www.tracemyfile.com/ is a service to track image usage. 
It use Mozilla/5.0 (compatible; tracemyfile/1.0) as UA. 

I think it should be added

**Comment by MaxGiting** [comment]
I agree. Would you like to do a PR for this user agent?

**Comment by alberto-bottarini** [comment]
Ok, give some hours

**Comment by alberto-bottarini** [comment]
https://github.com/JayBizzle/Crawler-Detect/pull/297
