### ISSUE TITLE
Extra (white)spaces in Fixtures/Crawlers.php

### ISSUE THREAD

**Issue by pavoltanuska** [JayBizzle/Crawler-Detect#307]
Some of the regular expressions in `$data` contain (what seems to me as) an extra whitespace at the end of the string, e.g.:

- https://github.com/JayBizzle/Crawler-Detect/blob/e5fbc685383a4b8f49183b3a646b193491cc14c5/src/Fixtures/Crawlers.php#L30
- https://github.com/JayBizzle/Crawler-Detect/blob/e5fbc685383a4b8f49183b3a646b193491cc14c5/src/Fixtures/Crawlers.php#L499
- https://github.com/JayBizzle/Crawler-Detect/blob/e5fbc685383a4b8f49183b3a646b193491cc14c5/src/Fixtures/Crawlers.php#L659

Is it supposed to be that way? Or is it something worth fixing?

I don't think it affects the functionality in any way, it just "looks off" in the output (to my eyes, at least).

**Comment by JayBizzle** [comment]
Hi,

Yes, I see what you are saying, but it think in some instances we left the space in on purpose to limit which user agents would be matched.

For example, I think we left the space on`^FDM ` incase there were any other user agents that started with `FDM` but has extra chars.

I think `HubSpot` and `Office` could have the spaces removed though 👍
