### ISSUE TITLE
Add http: to the generic regex?

### ISSUE THREAD

**Issue by JayBizzle** [JayBizzle/Crawler-Detect#31]
See #30

**Comment by romaricdrigon** [comment]
Good thing!

Some examples I found:
```
Mozilla/5.0 (compatible; +http://tweetedtimes.com)
Mozilla/5.0 (compatible; Embedly/0.2; http://support.embed.ly/)
Mozilla/5.0 (compatible) Feedfetcher-Google;(+http://www.google.com/feedfetcher.html)
Mozilla/5.0 (compatible; Butterfly/1.0; +http://labs.topsy.com/butterfly/) Gecko/2009032608 Firefox/3.0.8
woriobot (+http://www.worio.com/)
```

**Comment by JayBizzle** [comment]
I have a few like this in my logs

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.101 Safari/537.11 AppEngine-Google; (+http://code.google.com/appengine; appid: s~michael-yee)`

Should `AppEngine-Google` classed as a bot?

Also, what about `MagpieRSS/0.72 (+http://magpierss.sf.net)`

I also have a lot like this in my logs `Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1) ;  Embedded Web Browser from: http://bsalsa.com/; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET CLR 1.1.4322; InfoPath.1)`

**Comment by romaricdrigon** [comment]
Technically, AppEngine-Google is an hosting. But then it means it is a programmatic connection, hence a crawler.
MagpieRSS should also be classified as a bot.

I don't know from Bsalsa. The webpage is in Chinese, maybe it's one of those less-known proprietary web browsers. I receive some hit from time to time to some Wiko web browser.

**Comment by JayBizzle** [comment]
Agreed, I think I will add `AppEngine-Google` and `MagpieRSS` but at the moment, i think adding `http:` might be a little bit too generic.

Also, if you don't mind me asking @romaricdrigon , how much data do you gather regarding user-agents on your project?

**Comment by romaricdrigon** [comment]
I had a few thousand log entries to dig in - not that much actually, but with a very high ratio of crawlers (~ 50-70%). We logged UA for some time as we had huge differences between bit.ly or goo.gl hit counts vs ours. Because we post content to social network, within seconds any link posted on a public account is visited by at least a dozen crawler, including Facebook checking the OG tags, some social search tools...
