### ISSUE TITLE
Incorrect agent result

### ISSUE THREAD

**Issue by VBMart** [JayBizzle/Crawler-Detect#318]
Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36(KHTML, like Gecko) Chrome\/69.0.3464.0 Safari\/537.36 Chrome-Lighthouse

**Comment by VBMart** [comment]
It's google page speed insights bot:
https://developers.google.com/speed/pagespeed/insights/

**Comment by JayBizzle** [comment]
Would you like to create a PR for this?

**Comment by VBMart** [comment]
I don't know, what i can do with Exclusion list. This user agent contains Mozilla, Chrome, Safari.

**Comment by VBMart** [comment]
Sorry. I misunderstood, how CrawlerDetector works. I think, that exclusion list is something else.

**Comment by JayBizzle** [comment]
Fixed in #319
