### ISSUE TITLE
"CRONO 54" detected as cron

### ISSUE THREAD

**Issue by xPaw** [JayBizzle/Crawler-Detect#323]
`Mozilla/5.0 (Linux; Android 5.1; CRONO 54 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36`

**Comment by xPaw** [comment]
I believe this also happens with Zeus:

`Mozilla/5.0 (Linux; Android 4.2.1; MAJESTIC Zeus21 Build/JOP40D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.72 Mobile Safari/537.36`

**Comment by JayBizzle** [comment]
Fixed, thanks 👍
