### ISSUE TITLE
Detect google bots

### ISSUE THREAD

**Issue by mort3za** [JayBizzle/Crawler-Detect#33]
Google now supports crawling ajax pages. But other bots don't.
I want to  check that bot is google or not. How can i do this check?
Thanks

**Comment by mort3za** [comment]
Wrote this:
```
	$userAgent = $_SERVER['HTTP_USER_AGENT'];
	$userAgent = strtolower($userAgent);
	if (strpos($userAgent,'google') !== false) {
		// is google, so act like normal user
		$isBot = false;
	}
```

**Comment by JayBizzle** [comment]
What is the user agent of the Google bot you are trying to block?

**Comment by mort3za** [comment]
Don't want to block, Just want to show normal (heavy ajax) webiste to all google bots.

**Comment by JayBizzle** [comment]
Ah yeah, got ya.

This kind of thing should be easier when I get round to solving #2
