### ISSUE TITLE
Please add new crawler/bot/user-agent: "worldping-api"

### ISSUE THREAD

**Issue by orukaz** [JayBizzle/Crawler-Detect#330]
Please add new crawler/bot/user-agent "worldping-api" detection (https://worldping.raintank.io / https://grafana.com/plugins/raintank-worldping-app).

**User-Agent: worldping-api**
(worldping-api is detectable via User-Agent, which is exactly: `worldping-api`)

Here are the request that are made to my webpage:
```
IP.........................USER AGENT............TIMESTAMP..............DATETIME
45.63.65.147      worldping-api        1559600256	2019-06-04 01:17:36
147.75.193.249        worldping-api        1559600256	2019-06-04 01:17:36
35.196.53.64        worldping-api        1559600257	2019-06-04 01:17:37
178.62.52.161        worldping-api        1559600257	2019-06-04 01:17:37
45.63.49.0        worldping-api        1559600257	2019-06-04 01:17:37
159.65.193.69        worldping-api	1559600255	2019-06-04 01:17:35
45.63.84.144        worldping-api	1559600256	2019-06-04 01:17:36
3.112.221.14        worldping-api	1559600257	2019-06-04 01:17:37
```

Worldping-API requests are made from different IPs, countries and servers, only thing which is always the same is User-Agent.

It would be super nice to detect wordping-api request via JayBizzle/Crawler-Detect.

**Comment by orukaz** [comment]
I already forked and made the changes and made "pull request" ;)

**Comment by JayBizzle** [comment]
Added in #331

**Comment by orukaz** [comment]
@JayBizzle , thank you ;)

**Comment by orukaz** [comment]
I updated package on my site and it works fine ;)
