### ISSUE TITLE
How can I test access to a page in my site

### ISSUE THREAD

**Issue by fastsol** [JayBizzle/Crawler-Detect#334]
I'm feature testing aspects of my site and want to make sure that certain bots are allowed through.  I can't seem to figure out how in a phpunit test to send the correct info to the page so the crawlerDetect picks it up.  The crawler works fine when running the page through an outside service but I can't seem to make it work in my test. It appears that simply setting the HTTP_USER_AGENT isn't enough to make it detect properly.

Can you please provide what I need to add to my test to make it work.  This is the test I have so far.
```php
/** @test */
	public function google_allowed()
	{
		factory(Product::class)->create(['is_default' => 1]);

		$response = $this->call('get', route('index'), [], [], [], ['HTTP_USER_AGENT' => 'Googlebot/2.1 (+http://www.google.com/bot.html)']);
		
		$response->assertViewIs('client.index');
    }
```
I'm running this in a Laravel project and have a middleware that redirects accordingly.   This is in the middleware, the rest of the middleware code is not relevant to this.  As I said this all works fine when running through a site such as http://www.botsimulator.com/ as I can test multiple agents including my local machine and the responses are correct.
```php
if(LaravelCrawlerDetect::isCrawler()){
			
			return $next($request);
		}
```

**Comment by JayBizzle** [comment]
Hi,

The only way i can see to get around this would be to do something like...

```php
$crawlerDetect = new CrawlerDetect($request->server());
if ($crawlerDetect->isCrawler()) {
        return $next($request);
}
```

This would assume you switch to use this library directly rather than the Laravel package version. Doesn't really matter which you use, both the same.

Hope this helps.

**Comment by fastsol** [comment]
Yes that worked great, thank you!  On another note, this user-agent Chrome (Desktop) 62.0.3202.94, PageSpeed 1.15-gt1.2, YSlow 3.1.8 is one that https://gtmetrix.com uses and it's coming across as not a bot, which I guess is correct.  But would it be logical to list this is a bot, I have no idea what your requirements are for considering something a bot.  OR is there a way to add a whitelist of site specific exclusions or something?  Otherwise I guess I could simply make a if() to allow it through if it really bothers me that much.
