### ISSUE TITLE
Incorrect agent result

### ISSUE THREAD

**Issue by wulixb** [JayBizzle/Crawler-Detect#337]
Mozilla/5.0 (Linux; Android 9; PCAM10 Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.110 Mobile Safari/537.36 hap/1.0.4.5/oppo com.nearme.instant.platform/1.0.4.0 com.wifi.quickapp.reader.free/1.8.0 ({"packageName":"com.oppo.launcher","type":"shortcut","extra":{"original":{"packageName":"com.oppo.instant.local.service","type":"url","extra":{}},"scene":"api"}})

**Comment by JayBizzle** [comment]
So you think this isn't a bot?

Can you give me more details?

Thanks
