### ISSUE TITLE
Telegram Bot is missing

### ISSUE THREAD

**Issue by alberto-bottarini** [JayBizzle/Crawler-Detect#338]
https://stackoverflow.com/questions/32440659/check-if-telegram-is-getting-data-of-link-user-agent-is-telegram

**Comment by JayBizzle** [comment]
I believe `TelegramBot` is already detected. You can test the user-agent here https://crawlerdetect.io/

Remember, the library detects if the user-agent is a bot, or not.....it does not determine which bot.

Thanks
