### ISSUE TITLE
Uncaught Error: Class not found

### ISSUE THREAD

**Issue by lordsyncrus** [JayBizzle/Crawler-Detect#342]
Hi,

Just installed via composer.
Everything goes fine but when testing with your example this error is shown:

Fatal error: Uncaught Error: Class 'Jaybizzle\CrawlerDetect\CrawlerDetect' not found in /home/***/***/crawtest.php:9 Stack trace: #0 {main} thrown in /home/***/***/crawtest.php on line 9

Where I am wrong?

Thank you.

**Comment by Mohsiniii** [comment]
I'm also facing the same error. Can you please help to get rid of this?
Thanks :)

**Comment by JayBizzle** [comment]
Need more info if you want some help
