### ISSUE TITLE
Amazon Simple Notification Service Agent user agent

### ISSUE THREAD

**Issue by rentalhost** [JayBizzle/Crawler-Detect#343]
When Amazon SNS is reporting to your server, you eventually will receive a "visit" from "Amazon Simple Notification Service Agent" user agent. Should it being considered as a crawler (although this is not)?

**Comment by JayBizzle** [comment]
What's the user agent?

**Comment by rentalhost** [comment]
Is exactly that `Amazon Simple Notification Service Agent`.

**Comment by JayBizzle** [comment]
Okay, I would agree that this needs adding. Would you like to do a PR for this?

Thanks

**Comment by rentalhost** [comment]
You decide! I can do it if you prefer, but feel free if it's easier for you to do it.

**Comment by JayBizzle** [comment]
We encourage contributions 👍
