### ISSUE TITLE
OPPO A33 Build/LMY47V

### ISSUE THREAD

**Issue by AAKempf** [JayBizzle/Crawler-Detect#348]
Hi!

This seems to be a bot, see also
[https://www.johnlarge.co.uk/blocking-aggressive-chinese-crawlers-scrapers-bots/](url)

```
Mozilla/5.0(Linux;Android 5.1.1;OPPO A33 Build/LMY47V;wv) AppleWebKit/537.36(KHTML,link Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36 LieBaoFast/4.51.3
Mozilla/5.0(Linux;Android 5.1.1;OPPO A33 Build/LMY47V;wv) AppleWebKit/537.36(KHTML,link Gecko) Version/4.0 Chrome/42.0.2311.138 Mobile Safari/537.36 Mb2345Browser/9.0
Mozilla/5.0(Linux;U;Android 5.1.1;zh-CN;OPPO A33 Build/LMY47V) AppleWebKit/537.36(KHTML,like Gecko) Version/4.0 Chrome/40.0.2214.89 UCBrowser/11.7.0.953 Mobile Safari/537.36
```

**Comment by JayBizzle** [comment]
Would you like to create a PR?

Thanks 👍

**Comment by AAKempf** [comment]
Yes, I'm ready to push.

**Comment by JayBizzle** [comment]
Okay, will await your PR. Thanks!

**Comment by AAKempf** [comment]
I got an error and don't know why at the moment.

Remote: Permission to JayBizzle/Crawler-Detect.git denied to AAKempf. unable to access 'https://github.com/JayBizzle/Crawler-Detect.git/': The requested URL returned error: 403

Password is correct, login works, but push failed

**Comment by JayBizzle** [comment]
You need to forked my repo, then push to your fork first. Then you can create a PR 👍

**Comment by AAKempf** [comment]
OK, thanks. I'm a newbie ;)

**Comment by JayBizzle** [comment]
No worries, we all have to start somewhere 😁
