### ISSUE TITLE
crawlerdetect.io hacked?

### ISSUE THREAD

**Issue by XAKEPEHOK** [JayBizzle/Crawler-Detect#350]
In browser I see http://screenshot.lvcdn.ru/321d0315b7.png

**Comment by JayBizzle** [comment]
Interesting, thanks for reporting. Don't think it has been hacked, the digital ocean server I was using expired so I guess someone else in now using that IP address. I'm looking for a cheaper (or free) alternative to digital ocean.

Thanks again 👍

**Comment by anoxyty007** [comment]
How can I use it with my php website?

**Comment by JayBizzle** [comment]
Fixed! 👍
