### ISSUE TITLE
Check url for potential bots

### ISSUE THREAD

**Issue by HappyLDE** [JayBizzle/Crawler-Detect#352]
Hello, this has passed as a non bot/crawler with this user agent:
Mozilla/5.1 (Windows NT 6.0; WOW64) AppleWebKit/537.37 (KHTML, like Gecko) Chrome/58.0.1145.75 Safari/537.37

However the url it visited is this:
/wp-content/plugins/bb-ultimate-addon/assets/css/uabb-admin-notice.css

It was a direct access to that url.

Same with this:
User agent:
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

Url visited:
/wp-login.php

I don't use WordPress so the result for them is a 404

The objective of some of those crawlers is to check for a given domain what kind of project they are using, in this case testing for WordPress

**Comment by JayBizzle** [comment]
Hi,

Thanks for taking the time create an issue.

Unfortunately, in this instance, it is not possible for us to do anything as those user-agents you have listed have no unique signature that can be used to identify them. We have no way of knowing if they are indeed genuine, or not.

Thanks 👍
