### ISSUE TITLE
New sc-downloader/2.0

### ISSUE THREAD

**Issue by MikeVL** [JayBizzle/Crawler-Detect#354]
User-Agent `sc-downloader/2.0 (http://www.searchconcepts.io)`

**Comment by JayBizzle** [comment]
Would you like to create a PR to add this?

Thanks 👍

**Comment by MikeVL** [comment]
@JayBizzle https://github.com/JayBizzle/Crawler-Detect/pull/355

**Comment by JayBizzle** [comment]
👍
