### ISSUE TITLE
PHP v7.4 compatibility: $glue and $pieces parameters in reverse order to implode()

### ISSUE THREAD

**Issue by aedart** [JayBizzle/Crawler-Detect#368]
There is a PHP v7.4 compatibility issue, in the `outputTxt()` method, found in `export.php`.
Could you please swap `$glue` and `$pieces` arguments for the `implode()` method, so that this package can be used in PHP v7.4?

**Comment by JayBizzle** [comment]
Will accept a PR for this 👍
