### ISSUE TITLE
DuckduckGo bot is going unfiltered

### ISSUE THREAD

**Issue by Abhirup-99** [JayBizzle/Crawler-Detect#370]

**Comment by MaxGiting** [comment]
Can you please provide an example of the user agent.

**Comment by Abhirup-99** [comment]
https://developers.whatismybrowser.com/useragents/explore/software_name/duckduckgo-favicons-bot/

**Comment by MaxGiting** [comment]
[Mozilla/5.0 (compatible; DuckDuckGo-Favicons-Bot/1.0; +http://duckduckgo.com)](https://crawlerdetect.io/?q=Mozilla/5.0%20(compatible;%20DuckDuckGo-Favicons-Bot/1.0;%20+http://duckduckgo.com))
[Mozilla/5.0 (compatible; DuckDuckGo-Favicons-Bot/1.0; http://duckduckgo.com)](https://crawlerdetect.io/?q=Mozilla/5.0%20(compatible;%20DuckDuckGo-Favicons-Bot/1.0;%20http://duckduckgo.com))
[Mozilla/5.0 (compatible; DuckDuckGo-Favicons-Bot/1.0; +http://duckduckgo.com)](https://crawlerdetect.io/?q=Mozilla/5.0%20(compatible;%20DuckDuckGo-Favicons-Bot/1.0;%20+http://duckduckgo.com))

All three user agents from the link you provided are detected as bots by crawler detect. Any user agent with the word `bot` is automatically detected.
