### ISSUE TITLE
Amazon CloudFront shouldn't be treated as crawler

### ISSUE THREAD

**Issue by sunnydavis** [JayBizzle/Crawler-Detect#409]
Amazon CloudFront is often the user agent for using CloudFront as reverse proxy / CDN so it's actually not a crawler but regular user requests.

**Comment by JayBizzle** [comment]
Fancy PRing that?

Thanks 👍🏻

**Comment by sunnydavis** [comment]
Sure, it's done.

**Comment by JayBizzle** [comment]
Merged 👍
