### ISSUE TITLE
Wrong bot detection with semicolon without spaces on both sides

### ISSUE THREAD

**Issue by vintikzzz** [JayBizzle/Crawler-Detect#427]
Hi!

We have UA like this:
`Mozilla/5.0 (Linux; U; Android 5.0; en-US; SM-N900S;iPhone: Build/LRX21V)`
And after exclusions it translates to this:
` ( U  en-US SM-N900SiPhone: /LRX21V)`
And after that it is catched by reqular expresion `/Siphon/i` as bot.

I think it will be good to fix such User-Agents before processing, just add additional space after semicolon if there is no.

**Comment by JayBizzle** [comment]
Fixed in #428 👍
