### ISSUE TITLE
OCTOPUS-CORE is detected as bot

### ISSUE THREAD

**Issue by vintikzzz** [JayBizzle/Crawler-Detect#429]
Hi!
We have ua:
```
Mozilla/5.0 (Linux; Android 9; OCTOPUS-CORE T8 Build/PPR1.181005.003) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36 YaApp_Android/9.50/apad YaSearchBrowser/9.50
```
So it was cached as bot with this:
```
/Octopus/i
```
Is it correct to use non case-sensitive regular expressions?

**Comment by JayBizzle** [comment]
Thanks, looks like this is indeed a false positive. Will release a fix soon 👍🏻

**Comment by JayBizzle** [comment]
Fix in https://github.com/JayBizzle/Crawler-Detect/releases/tag/v1.2.103
