### ISSUE TITLE
Microsft office bot ?

### ISSUE THREAD

**Issue by malohtie** [JayBizzle/Crawler-Detect#430]
Hi, 
i wonder why this is marked as bot ?
```
Microsoft Office/16.0 (Microsoft Outlook 16.0.13228; Pro), Mozilla/4.0 (compatible; ms-office; MSOffice 16)
```

if user read emails with microsoft outlook i think it not a bot right ?

**Comment by gplumb** [comment]
Hi Mohamed

Depends on the Outlook email client. The Android version of Outlook came by
way of an acquisition and that product had spiders that would cache content
and reformat it - which is arguably bot behaviour.

There was conversation around adding additional classifications to the
crawlers, but I think that kind of tailed off.

I'd be open to starting that work on NetCrawlerDetect if there was enough
motivation from others to help :-)


G

**Comment by JayBizzle** [comment]
Definitely bot behaviour in my view unless you can persuade me otherwise 👍
