### ISSUE TITLE
Incorrect agent result

### ISSUE THREAD

**Issue by LinusGeffarth** [JayBizzle/Crawler-Detect#439]
> Mozilla/5.0 (Linux; Android 7.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.175 Mobile Safari/537.36 Chrome-Lighthouse

...is properly detected as bot in the [web demo](https://crawlerdetect.io), but is NOT detected as such in code.

**Comment by JayBizzle** [comment]
Just tested this locally...

```php
use Jaybizzle\CrawlerDetect\CrawlerDetect;

$cd = new CrawlerDetect();

var_dump($cd->isCrawler('Mozilla/5.0 (Linux; Android 7.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.175 Mobile Safari/537.36 Chrome-Lighthouse'));

// Output: bool(true)
```

Have you got the latest version installed?

🤷

**Comment by LinusGeffarth** [comment]
Thanks for checking so quickly. You're right, my implementation was wrong. Sorry for the false alarm!
