### ISSUE TITLE
Missing Crawler

### ISSUE THREAD

**Issue by awolf-pizzeria** [JayBizzle/Crawler-Detect#471]
This seems to be a crawler, too: Mozilla/5.0 (compatible; Seekport Crawler; http://seekport.com/)

Regards, Andreas

**Comment by JayBizzle** [comment]
This is already detected as a bot

https://crawlerdetect.io/?q=Mozilla/5.0%20(compatible;%20Seekport%20Crawler;%20http://seekport.com/)
