### ISSUE TITLE
OhDear Uptime Checker

### ISSUE THREAD

**Issue by Clovelock** [JayBizzle/Crawler-Detect#473]
Hi, not sure what to add into a PR so hopefully you can answer / do it.

The service OhDear: https://ohdear.app/docs/faq/what-is-the-oh-dear-checker

It states the user-agents as:

"Mozilla/5.0 (compatible; OhDear/1.1; +https://ohdear.app/checker; brokenLinks)"
and
"Mozilla/5.0 (compatible; OhDear/1.1; +https://ohdear.app/checker; mixedContent)"

**Comment by JayBizzle** [comment]
Thanks, will add this soon 👍🏻

**Comment by JayBizzle** [comment]
Just looked into this and we already both of these user agents as bots

See [here](Mozilla/5.0 (compatible; OhDear/1.1; +ohdear.app/checker; brokenLinks)) and [here](https://crawlerdetect.io/?q=Mozilla/5.0%20(compatible;%20OhDear/1.1;%20+ohdear.app/checker;%20mixedContent))
