### ISSUE TITLE
support broken-link-checker

### ISSUE THREAD

**Issue by staabm** [JayBizzle/Crawler-Detect#476]
would be great if this lib would detect https://github.com/stevenvachon/broken-link-checker as a crawler

the user agent is `broken-link-checker/0.8.0 Node.js/14.16.0 (OS X; x64)` see https://github.com/stevenvachon/broken-link-checker#useragent

**Comment by JayBizzle** [comment]
We do! [See here](https://crawlerdetect.io/?q=broken-link-checker/0.8.0%20Node.js/14.16.0%20(OS%20X;%20x64))

**Comment by staabm** [comment]
Peferct thx. Couldnt find the ua in the repo :-)
