### ISSUE TITLE
Incorrect agent result

### ISSUE THREAD

**Issue by damarinov1** [JayBizzle/Crawler-Detect#482]
Inboxb0t-Image/2.0

**Comment by ffonly81** [comment]
These are also incorrect, user agent: **incorrect result**
Mozilla/5.0 (compatible; statdom.ru/Bot; +http://statdom.ru/bot.html): **Bot**
XenForo/1.5 (http://any_domain/forum): **XenForo/**
Mozilla/5.0 (Windows NT 6.1; Win64; x64; +http://url-classification.io/wiki/index.php?title=URL_server_crawler) KStandBot/1.0: **URL_server_crawl** 
Mozilla/5.0 (compatible; Barkrowler/0.9; +https://babbar.tech/crawler): **owler**
P3P Validator: **Validator**
