### ISSUE TITLE
Incorrect agent result

### ISSUE THREAD

**Issue by timo002** [JayBizzle/Crawler-Detect#485]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 ForusP

ForusP is a security company and uses Qualys to perform automated tests on websites. Above useragent they use to crawl your site.

**Comment by JayBizzle** [comment]
Thanks ❤️
