### ISSUE TITLE
Empty user agent

### ISSUE THREAD

**Issue by SoranDK** [JayBizzle/Crawler-Detect#503]
I see that my web-server-provider has a statistics section about bots and that they also identify visits with empty user-agent as bots.

Is it worth checking for this before running the exclude?

Their stats say 513 visits of that type on my site this year.

**Comment by JayBizzle** [comment]
Can we safely say an empty user-agent is a bot?

**Comment by SoranDK** [comment]
That is a good question... I don't have an answer... 

We probably don't know all browsers or user configurations so the rules are our best guesses and will probably always have an amount of both false positives and negatives... Can we safely say that all user-agents containing "reader" is one?

I would just suggest that there are perhaps not many ordinary user with a setup showing no user agents at all.

But I am new to this plugin so I will gladly yield to those with more experience to evaluate if that would result in an unreasonable amount of false positives :-)
