### ISSUE TITLE
Could we add lscache_runner as user agent?

### ISSUE THREAD

**Issue by therampagerado** [JayBizzle/Crawler-Detect#526]
**lscache_runner** is a user agent for cache warmers for LSCache from Litespeed servers. Currently if our project uses Crawler-Detect those hits are not treated as bots.

**lscache_runner iPhone** is another user agent for their mobile crawling.

Documentation: https://docs.litespeedtech.com/lscache/lscps/crawler/

Thanks!

**Comment by JayBizzle** [comment]
Looks good, create a PR 👍

**Comment by therampagerado** [comment]
I have issues with the tests. Should we only leave 'lscache_runner'? Will it cover the other UA?

**Comment by JayBizzle** [comment]
Yes, just add that one, as it will cover the other, that's why the tests are failing 👍🏻

**Comment by therampagerado** [comment]
Thanks!

New PR - https://github.com/JayBizzle/Crawler-Detect/pull/528
