### ISSUE TITLE
Crawler to add: RuxitSynthetic

### ISSUE THREAD

**Issue by micheletnc** [JayBizzle/Crawler-Detect#537]
It seems "RuxitSynthetic" is a string used by browser's monitoring tool [ActiveGate](https://docs.dynatrace.com/docs/setup-and-configuration/dynatrace-activegate/supported-connectivity-schemes-for-activegates#activegate-headers) by Dynatrace. While DynatraceSynthetic is already in the crawler list, RuxitSynthetic is currently missing.

Here a bunch of user-agents (they also depend by a timestamp):

- Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.99 Safari/537.36 RuxitSynthetic/1.0 v119975163693 t1975984516666483988 ath87850d94 altpub cvcv=2 smf=0
- Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.99 Safari/537.36 RuxitSynthetic/1.0 v119976524957 t1975984516666483988 ath87850d94 altpub cvcv=2 smf=0
- Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.99 Safari/537.36 RuxitSynthetic/1.0 v119971670291 t6995014076026012873 ath87850d94 altpub cfeatureHash=fqt cvcv=2 smf=0
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 Edg/104.0.1293.63 RuxitSynthetic/1.0 v119970203266 t2855531618417403483 ath889cb9b1 altpub cfeatureHash=f cvcv=2 smf=0
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 Edg/104.0.1293.63 RuxitSynthetic/1.0 v119971099991 t2855531618417403483 ath889cb9b1 altpub cfeatureHash=f cvcv=2 smf=0
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 RuxitSynthetic/1.0 v119967560568 t7328515548161586149 ath87850d94 altpub cvcv=2 smf=0
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 RuxitSynthetic/1.0 v119968013567 t7328515548161586149 ath87850d94 altpub cvcv=2 smf=0
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 RuxitSynthetic/1.0 v119978897576 t7328515548161586149 ath87850d94 altpub cvcv=2 smf=0
- Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.99 Safari/537.36 RuxitSynthetic/1.0 v119974844462 t6995014076026012873 ath87850d94 altpub cfeatureHash=fqt cvcv=2 smf=0
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 Edg/104.0.1293.63 RuxitSynthetic/1.0 v119966567204 t2855531618417403483 ath889cb9b1 altpub cfeatureHash=f cvcv=2 smf=0

**Comment by JayBizzle** [comment]
Fixed in #538
