### ISSUE TITLE
IP detection?

### ISSUE THREAD

**Issue by dchubad** [JayBizzle/Crawler-Detect#545]
This looks a nice script, but I don't see any IP pattern matching? We all know headers can easily be spoofed. 
When browsing the scripts, I did not see any Reverse DNS lookups, nothing to check the Bot IP against the User Agent which means anyone could write a simple script using a fake header could pretend to be any crawler. This is why people like Bing or Google provide not only the User Agent but also the IP's that they use so that website owners can verify if they are authentic bots.

By the way, there are **zero instructions** on installing this script. Where the hell are we meant to extract the directory to?
Running composer require jaybizzle/crawler-detect seems to only install dependencies. I am xampp on using windows 11 where it is installed in c:/xampp

**Comment by JayBizzle** [comment]
Regarding IP addresses - see https://github.com/JayBizzle/Crawler-Detect/issues/149

Regarding installation instructions - composer installation works fine [68 million other installs agree](https://packagist.org/packages/jaybizzle/crawler-detect/stats).

Maybe you can find some help with your install issue on StackOverflow or similar.
