### ISSUE TITLE
Empty user agent

### ISSUE THREAD

**Issue by timersys** [JayBizzle/Crawler-Detect#75]
If its empty user agent is treated as a crawler? Can we add a simple setting variable to do that? That all empty UA should be treated as crawler

**Comment by JayBizzle** [comment]
Hi,

Thanks for the suggestion. I can understand why you may want this adding, but in my opinion, keeping CrawlerDetect matter of fact is the way go i.e. it is a bot, or not.

In my opinion, an empty user agent is just a guess, and i dont think this library should guess. I know your suggestion will make this user configurable, but you could just as easliy do this

```php
$crawlerdetect = new CrawlerDetect();

$useragent = $_SERVER['HTTP_USER_AGENT'];

if(empty($useragent) || $crawlerdetect->isCrawler($useragent) {
    // it is a bot
}
```

Unless you can convince me other wise :smile:
